"""Phoenix Evaluators — LLM-as-Judge and code evals for quality scoring.

Runs evaluations on traces to demonstrate agent quality:
1. Forensic Hallucination Eval — are findings grounded in tool output?
2. Tool Calling Accuracy Eval — were tools called correctly?
3. Agent Trajectory Eval — was the investigation sequence logical?
4. Confidence Calibration Eval — are confidence scores accurate?

These can run:
- Online (continuously on incoming traces)
- Offline (as experiments against benchmark datasets)
"""

import json
from typing import Any

# Phoenix evals (open source)
from phoenix.evals import (
    OpenAIModel,
    llm_classify,
)


# ──────────────────────────────────────────────────
# EVAL 1: Forensic Hallucination
# ──────────────────────────────────────────────────

FORENSIC_HALLUCINATION_TEMPLATE = """
You are evaluating a forensic investigation finding for hallucination.

The finding was generated by an AI forensic agent analyzing digital evidence.
Below are the actual tool outputs (ground truth) and the finding the agent produced.

## Actual Tool Outputs:
{reference}

## Agent's Finding:
{response}

## Evaluation Criteria:
A finding is FACTUAL if:
- Every claim can be traced to a specific tool output above
- Timestamps cited match tool output exactly
- File names, process names, and paths match tool output
- No additional claims are made beyond what tools returned

A finding is HALLUCINATED if:
- It contains claims not present in any tool output
- It cites timestamps, files, or processes that don't appear in tool output
- It makes logical leaps not supported by the evidence

Classify as either "factual" or "hallucinated".
"""

FORENSIC_HALLUCINATION_RAILS = ["factual", "hallucinated"]


# ──────────────────────────────────────────────────
# EVAL 2: Tool Calling Accuracy
# ──────────────────────────────────────────────────

TOOL_CALLING_TEMPLATE = """
You are evaluating whether a forensic tool was called correctly.

## Context:
The agent was investigating {question} and decided to call:
Tool: {tool_name}
Arguments: {tool_args}

## Tool Output:
{response}

## Evaluation Criteria:
A tool call is CORRECT if:
- The tool chosen is appropriate for what the agent is investigating
- The arguments are valid (correct paths, valid parameters)
- The tool would reasonably help answer the agent's current question

A tool call is INCORRECT if:
- Wrong tool for the situation (e.g., using Amcache to prove execution)
- Invalid arguments (wrong path, malformed parameters)
- Tool is redundant (already called with same params)

Classify as either "correct" or "incorrect".
"""

TOOL_CALLING_RAILS = ["correct", "incorrect"]


# ──────────────────────────────────────────────────
# EVAL 3: Agent Trajectory Quality
# ──────────────────────────────────────────────────

TRAJECTORY_TEMPLATE = """
You are evaluating the quality of a forensic investigation trajectory.

## Investigation Steps (in order):
{response}

## Evaluation Criteria:
A trajectory is LOGICAL if:
- Steps follow a sensible investigation sequence
- Each step builds on previous findings
- No unnecessary repetition or circular investigation
- Self-correction happens when contradictions are found
- The agent stops when evidence is sufficient (doesn't over-investigate)

A trajectory is ILLOGICAL if:
- Steps are random or don't build on each other
- Important obvious checks are skipped
- The agent keeps running the same tools repeatedly
- Contradictions are ignored
- The agent stops too early with unresolved issues

Classify as either "logical" or "illogical".
"""

TRAJECTORY_RAILS = ["logical", "illogical"]


# ──────────────────────────────────────────────────
# EVAL 4: Confidence Calibration (Code-based)
# ──────────────────────────────────────────────────

def evaluate_confidence_calibration(finding: dict) -> dict:
    """Code evaluator: Is the confidence score appropriate for the evidence?
    
    Rules:
    - CONFIRMED requires 2+ independent sources in evidence_ids
    - INFERRED requires exactly 1 source
    - UNVERIFIED means no evidence references
    - CONTRADICTED means sources disagree (must be flagged)
    """
    confidence = finding.get("confidence", "UNVERIFIED")
    sources = finding.get("sources", [])
    evidence_ids = finding.get("evidence_ids", [])
    
    source_count = max(len(sources), len(evidence_ids))
    
    if confidence == "CONFIRMED" and source_count < 2:
        return {
            "label": "miscalibrated",
            "score": 0.0,
            "explanation": f"CONFIRMED requires 2+ sources, but only {source_count} found",
        }
    elif confidence == "INFERRED" and source_count >= 2:
        return {
            "label": "miscalibrated",
            "score": 0.5,
            "explanation": f"Could be CONFIRMED — has {source_count} sources but labeled INFERRED",
        }
    elif confidence == "UNVERIFIED" and source_count >= 1:
        return {
            "label": "miscalibrated",
            "score": 0.5,
            "explanation": f"Has {source_count} source(s) but labeled UNVERIFIED",
        }
    else:
        return {
            "label": "calibrated",
            "score": 1.0,
            "explanation": f"Confidence '{confidence}' matches source count ({source_count})",
        }


# ──────────────────────────────────────────────────
# Runner: Evaluate a complete investigation
# ──────────────────────────────────────────────────

async def evaluate_investigation(
    findings: list[dict],
    tool_outputs: list[dict],
    trajectory: list[str],
) -> dict:
    """Run all evaluators on a completed investigation.
    
    Returns summary scores for the accuracy report.
    """
    results = {
        "hallucination_scores": [],
        "tool_calling_scores": [],
        "trajectory_score": None,
        "confidence_calibration": [],
    }
    
    # Confidence calibration (code-based, always runs)
    for finding in findings:
        cal_result = evaluate_confidence_calibration(finding)
        results["confidence_calibration"].append({
            "finding_id": finding.get("id"),
            **cal_result,
        })
    
    # Summary
    cal_scores = [r["score"] for r in results["confidence_calibration"]]
    results["summary"] = {
        "total_findings": len(findings),
        "confidence_calibration_avg": sum(cal_scores) / len(cal_scores) if cal_scores else 0,
        "hallucination_rate": 0,  # TODO: from LLM eval
        "trajectory_quality": "pending",  # TODO: from LLM eval
    }
    
    return results
