"""Guardrail Pipeline — The gate between agent and user.

NO FINDING REACHES THE USER WITHOUT PASSING THROUGH THIS.

Pipeline:
  Agent generates finding
    → Deterministic checks (instant, no LLM)
    → Evaluator scores it (hallucination check)
    → Improvement loop consulted (past mistakes check)
    → Decision: APPROVE / FLAG / BLOCK

This is architecturally enforced — not prompt-based.
The agent physically cannot bypass this layer.
"""

import json
from typing import Optional
from dataclasses import dataclass

from opentelemetry import trace
from openinference.semconv.trace import SpanAttributes

from sift_defender.phoenix.evaluator import ForensicEvaluator, EvalResult
from sift_defender.phoenix.improvement_loop import ImprovementLoop


@dataclass
class GuardrailDecision:
    """The final decision on whether a finding reaches the user."""
    finding_id: str
    action: str          # "APPROVE", "FLAG_FOR_REVIEW", "BLOCK"
    score: float         # 0.0-1.0 confidence in the finding
    label: str           # "factual", "partially_supported", "hallucinated"
    issues: list[str]    # Problems found
    explanation: str     # Why this decision was made
    
    @property
    def should_show_user(self) -> bool:
        return self.action != "BLOCK"


class GuardrailPipeline:
    """Enterprise guardrail — evaluates and gates every finding.
    
    Usage:
        pipeline = GuardrailPipeline()
        
        # For each finding the agent produces:
        decision = pipeline.evaluate(finding, tool_outputs)
        
        if decision.should_show_user:
            show_to_user(finding, confidence=decision.label)
        else:
            log_blocked(finding, reason=decision.explanation)
    """
    
    def __init__(self):
        self.evaluator = ForensicEvaluator()
        self.improvement = ImprovementLoop()
        self.tracer = trace.get_tracer("sift_defender.guardrail_pipeline")
        
        # Stats
        self._total_processed = 0
        self._approved = 0
        self._flagged = 0
        self._blocked = 0
    
    def evaluate(
        self,
        finding: dict,
        tool_outputs: list[dict],
    ) -> GuardrailDecision:
        """Run the full guardrail pipeline on a finding.
        
        This is the ONLY way findings reach the user.
        
        Args:
            finding: The finding generated by the agent
            tool_outputs: All tool outputs from this investigation
            
        Returns:
            GuardrailDecision with action (APPROVE/FLAG/BLOCK)
        """
        with self.tracer.start_as_current_span(
            "guardrail_pipeline",
            attributes={
                SpanAttributes.OPENINFERENCE_SPAN_KIND: "GUARDRAIL",
                SpanAttributes.INPUT_VALUE: json.dumps({
                    "finding_id": finding.get("id"),
                    "title": finding.get("title"),
                    "confidence": finding.get("confidence"),
                })[:500],
            },
        ) as span:
            self._total_processed += 1
            
            # Stage 1: Evaluator (deterministic + optional LLM)
            eval_result = self.evaluator.evaluate_finding(finding, tool_outputs)
            
            # Stage 2: Check against past mistakes
            past_hints = self.improvement.get_pre_investigation_hints()
            extra_issues = self._check_against_history(finding, past_hints)
            
            all_issues = eval_result.issues + extra_issues
            
            # Stage 3: Final decision
            if eval_result.score == 0.0 or len(all_issues) >= 3:
                action = "BLOCK"
                self._blocked += 1
            elif eval_result.score < 1.0 or len(all_issues) >= 1:
                action = "FLAG_FOR_REVIEW"
                self._flagged += 1
            else:
                action = "APPROVE"
                self._approved += 1
            
            decision = GuardrailDecision(
                finding_id=finding.get("id", "?"),
                action=action,
                score=eval_result.score,
                label=eval_result.label,
                issues=all_issues,
                explanation=self._explain_decision(action, all_issues, finding),
            )
            
            # Record in span
            span.set_attribute(SpanAttributes.OUTPUT_VALUE, json.dumps({
                "action": action,
                "score": decision.score,
                "label": decision.label,
                "issues_count": len(all_issues),
            }))
            span.set_attribute("guardrail.action", action)
            span.set_attribute("guardrail.score", decision.score)
            span.set_attribute("guardrail.passed", decision.should_show_user)
            
            return decision
    
    def _check_against_history(self, finding: dict, hints: list[str]) -> list[str]:
        """Check if this finding matches patterns we've gotten wrong before."""
        issues = []
        title = finding.get("title", "").lower()
        
        for hint in hints:
            hint_lower = hint.lower()
            # If hint warns about execution claims and finding makes one
            if "execution" in hint_lower and any(w in title for w in ["executed", "ran"]):
                if finding.get("confidence") == "CONFIRMED":
                    issues.append("Historical pattern: past over-confidence on execution claims")
            # If hint warns about network claims
            if "network" in hint_lower and any(w in title for w in ["c2", "beacon", "network"]):
                issues.append("Historical pattern: past hallucinations on network claims")
        
        return issues
    
    def _explain_decision(self, action: str, issues: list[str], finding: dict) -> str:
        """Generate human-readable explanation for the decision."""
        if action == "APPROVE":
            return f"Finding '{finding.get('title', '?')}' passed all checks. Grounded in evidence."
        elif action == "FLAG_FOR_REVIEW":
            return (
                f"Finding '{finding.get('title', '?')}' needs human review. "
                f"Issues: {'; '.join(issues)}"
            )
        else:
            return (
                f"Finding '{finding.get('title', '?')}' BLOCKED — likely hallucination. "
                f"Issues: {'; '.join(issues)}"
            )
    
    @property
    def metrics(self) -> dict:
        """Get pipeline metrics."""
        return {
            "total_processed": self._total_processed,
            "approved": self._approved,
            "flagged": self._flagged,
            "blocked": self._blocked,
            "block_rate": round(self._blocked / max(1, self._total_processed), 3),
            "evaluator_metrics": self.evaluator.get_metrics(),
            "improvement_trend": self.improvement.get_accuracy_trend(),
        }
